# Generated by Django 5.2.8 on 2025-11-27 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('multilayer', 'Multilayer')], default='switch', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('state', models.BooleanField(default=False)),
                ('is_access', models.BooleanField(default=True)),
                ('native', models.PositiveIntegerField(default=1)),
                ('allowed_vlan', models.CharField(blank=True, max_length=200, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='NetVision_Studio.device')),
            ],
            options={
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAC', models.CharField(max_length=17, unique=True)),
                ('ip_host', models.GenericIPAddressField(protocol='IPv4')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('connected_toInt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NetVision_Studio.interface')),
            ],
        ),
        migrations.CreateModel(
            name='ConfLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_mode', models.CharField(max_length=20)),
                ('new_mode', models.CharField(max_length=20)),
                ('prev_native', models.PositiveIntegerField()),
                ('new_native', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetVision_Studio.interface')),
            ],
        ),
        migrations.CreateModel(
            name='SyslogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
                ('severity', models.PositiveIntegerField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NetVision_Studio.device')),
            ],
        ),
        migrations.CreateModel(
            name='TopologyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_a', to='NetVision_Studio.device')),
                ('device_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_b', to='NetVision_Studio.device')),
                ('interface_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_a', to='NetVision_Studio.interface')),
                ('interface_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_b', to='NetVision_Studio.interface')),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('vlan_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Vlan_IntAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_native', models.BooleanField(default=False)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_assignment', to='NetVision_Studio.interface')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetVision_Studio.vlan')),
            ],
        ),
    ]
