# Generated by Django 5.2.8 on 2025-11-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetVision_Studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='vlan_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
