# Generated by Django 5.2.8 on 2025-11-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetVision_Studio', '0002_alter_vlan_unique_together_alter_vlan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(default='cisco', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
