# Generated by Django 5.2.8 on 2025-12-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetVision_Studio', '0003_device_password_device_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='allowed_vlan',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='native',
        ),
        migrations.RemoveField(
            model_name='vlan_intassignment',
            name='is_native',
        ),
    ]
