# Generated by Django 5.2.8 on 2025-12-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetVision_Studio', '0004_remove_interface_allowed_vlan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan_intassignment',
            name='is_native',
            field=models.BooleanField(default=False),
        ),
    ]
